#!/bin/bash 

set -xa
date

# #### 01/19/00 ###############################
# SETUP RAW HRLY PROCESSING VARIABLES
# #############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export outid="LL$job"
export jobid="${outid}.o${pid}"
export DATA=${DATAROOT:?}/${jobid:?}
export TMPDIR=$DATA
mkdir $DATA

cd $DATA

export cyc=${cyc:-${cyc}}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-sfcship}
export RUN=${RUN:-sfcship}
export krun=${krun:-2}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
#export outid="LL$job"
#export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDCOM  - Copy Files From TMPDIR to $comout
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEsfcship=${HOMEsfcship:-${PACKAGEROOT}}
export EXECsfcship=${HOMEsfcship}/exec
export USHgraph=${HOMEsfcship}/util/ush

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################################
# Define comout directory
##############################################
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.$PDY}
mkdir -p $COMOUT
 
#############################################################
# Execute the script
#############################################################
$HOMEsfcship/scripts/exrw2.sh.ecf


#############################################################

if [ -e "$pgmout" ]; then
 cat $pgmout
fi

##############################
# Remove the Temporary working directory
##############################

if [ "${KEEPDATA}"!=YES ]; then
  rm -fr $DATA
fi

date

