#!/bin/bash  

set -xa
date
 
# #############################################
# SETUP RW3 PROCESSING CONTROL SHELL VARIABLES
# #############################################
 
####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$

export DATA=${DATAROOT:?}/${jobid:?}
export TMPDIR=$DATA
mkdir $DATA

cd $DATA

export cyc=${cyc:-${cyc}}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-sfcship}
export RUN=${RUN:-sfcship}      
export krun=${krun:-3}       # Indicator set for North American sfcplot and MSLP analysis

# variables that control processing

####################################
# SENDCOM  - Copy Files From TMPDIR to $comout
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
 
####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# Specify Execution Areas
####################################
export HOMEsfcship=${HOMEsfcship:-${NWROOT}/sfcship.${sfcship_ver}}
export EXECsfcship=${HOMEsfcship}/exec
export USHgraph=${HOMEsfcship}/util/ush

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################################
# Define comout directory
##############################################
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.$PDY}
mkdir -p $COMOUT

##############################################
# Execute the script
##############################################
$HOMEsfcship/scripts/exrw3.sh.ecf

##############################################

if [ -e "$pgmout" ]; then
 cat $pgmout
fi

##############################
# Remove the Temporary working directory
##############################

if [ "${KEEPDATA}"!=YES ]; then
  rm -fr $DATA
fi

date

