#!/bin/bash

set -xa
date

# #############################################
# SETUP RW5 PROCESSING CONTROL SHELL VARIABLES
# #############################################
 
####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export outid="LL$job"
export jobid="${outid}.o${pid}"
export DATA=${DATAROOT:?}/${jobid:?}
export TMPDIR=$DATA
mkdir $DATA

cd $DATA

export cyc=${cyc:-${cyc}}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-sfcship}
export RUN=${RUN:-sfcship}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
 
####################################
# Determine Job Output Name on System
####################################
#export outid="LL$job"
#export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# Specify Execution Areas
####################################
export HOMEsfcship=${HOMEsfcship:-${PACKAGEROOT}/sfcship.${sfcship_ver}}
export EXECsfcship=${HOMEsfcship}/exec
export USHgraph=${HOMEsfcship}/util/ush

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################################
# Define comout directory
##############################################
export COMOUT=${COMOUT:-$(compath.py ${envir}/${NET}/${ver}/${RUN}.$PDY})}
mkdir -p $COMOUT

##############################################
# Execute the script
##############################################
$HOMEsfcship/scripts/exrw5.sh

##############################################

if [ -e "$pgmout" ]; then
 cat $pgmout
fi

##############################
# Remove the Temporary working directory
##############################

if [ "${KEEPDATA}"!=YES ]; then
  rm -fr $DATA
fi

date

