#!/bin/bash -l

#. /usrx/local/prod/lmod/lmod/init/bash (commented out until this is found on WCOSS2)


module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich/8.1.4
w3nco_ver=2.4.1
bufr_ver=11.4.0
w3emc_ver=2.7.3
bacio_ver=2.4.1

#module load prod_envir/1.0.3     # venus & mars /dcom #(commentet out until sure if needed on WCOSS2)
module load w3nco/${w3nco_ver:?}
module load bufr/${bufr_ver:?}
module load w3emc/${w3emc_ver:?}
module load bacio/${bacio_ver:?}

#inlcuded in module load bufr_dump, also includes dumpjb
#export bufr_dumplist_ver=2.0.2
#module load bufr_dumplist/${bufr_dumplist_ver:?}

#module use /apps/ops/test/nco/modulefiles/core
module load bufr_dump/2.0.0
module list

export raws_ver=1.0.0

#export NWROOT=/lfs/h2/emc/obsproc/noscrub/Steve.Stegall/gitwkspc/EMC_sfcship.v1.0.0
export NWROOT=/lfs/h2/emc/obsproc/noscrub/Steve.Stegall/githubwkspc/sfcship
 ${NWROOT}/jobs/JRW5


